version: "3.9"

services:
  php:
    build:
      context: .
      dockerfile: Dockerfile.php
    container_name: my-php
    ports:
      - "8000:8000"
    volumes:
      - ../:/var/www/html
    networks:
      - my-network
    depends_on:
      - mysql
      - redis
      - mongo
  mysql:
    image: mysql:8.0
    container_name: my-mysql
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: mydb
      MYSQL_USER: myuser
      MYSQL_PASSWORD: mypassword
      MYSQL_ROOT_PASSWORD: myrootpassword
    volumes:
      - ./mysql:/var/lib/mysql
    networks:
      - my-network
  redis:
    image: redis:latest
    container_name: my-redis
    restart: always
    ports:
      - "6379:6379"
    networks:
      - my-network
  mongo:
    image: mongo:latest
    container_name: my-mongo
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - ./mongo:/data/db
    networks:
      - my-network

networks:
  my-network:
